import type { Metadata } from "next";
import { siteConfig } from "./siteConfig";

export const metadata: Metadata = {
  metadataBase: new URL("#"),
  title: siteConfig.name || "Innovation Management Platform",
  description: siteConfig.description || "Generated by Hackathon Merchants",
  keywords: ["Marketing", "Database", "Software"],
  authors: [
    {
      name: "yourname",
      url: "",
    },
  ],
  creator: "yourname",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    creator: "@yourname",
  },
  icons: {
    icon: "#",
  },
};